### ISSUE TITLE
ListAlerts page changes

### ISSUE THREAD

**Issue by 3nvi** [panther-labs/panther#1015]
### Background
The current `Log Analysis` -> `Alerts` page shows the alerts that have been triggered, but does not provide the same usability found elsewhere in the application such as some of the sort/filtering options the `Log Analysis` -> `Rules` page contains.

**Note**: filtering additions should be implemented first as sorting has its own challenges.

Filtering capability:
- [x] Severity Level (single level)
- [ ] Title (name contains)
- [ ] Alert ID (multiple IDs)
- [ ] Events (count range)
- [ ] Created At (date range)
- [ ] Last Matched At (date range)

Sorting capability:
- [ ] Title
- [ ] Severity Level
- [ ] Alert ID
- [ ] Events count
- [ ] Created At
- [ ] Last Matched At
