### ISSUE TITLE
Merge Log Analysis and Cloud Security Alerting Pipelines

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1095]
## Description

Historically, Cloud Security and Log Analysis have entirely separate pipelines, which do approximately the same thing, before landing in the shared alerting pipeline, the `alert-forwarder` lambda.

This causes confusion in the small (but meaningful) ways in which the two pipelines differ and adds both code and infrastructure complexity to managing the two pipelines independently. Additionally, the Cloud Security pipeline does not make use of the long term storage of generated alerts. 

By merging the Cloud Security and Log Analysis pipelines into one pipeline (based on the existing log analysis alerting pipeline), we can reduce user confusion/inconsistent application behavior in addition to reducing code and infrastructure complexity.

## RFC

> **_Note:_** To be updated by the feature owner once completed

## Design

> **_Note:_** To be updated by the feature owner once completed

## Status and Stakeholders

- [ ] Epic created [product] @jacknagz 
- [ ] RFC written [feature owner] @nhakmiller 
- [ ] Frontend assigned [frontend]
- [ ] Designs mocked [designer] 
- [ ] Stories planned [fe/be]
- [ ] Stories executed [fe/be]
- [ ] Validation [product/feature owner]

#### User Story

As a security engineer
I want to have the ability to write a detection in the style of a rule
To detect insecure infrastructure in the same manner I would analyze logs

#### Acceptance Criteria

- Policy Detections should be based on snapshots (or diffs) to obtain the transparency of knowing which resource triggered the alerts
- Policies can use the same override, deduplication, merging, and thresholding functions that Rules currently have
- When a Policy-based detection Returns "True", an alert would be generated, which is the opposite of what happens today
- The Resource <> Policy workflows would remain the same
- When creating Policy-based Alerts, I can interpolate the resource ID which triggered the alert.

### Documentation

> **_Note:_** This is a requirement for every Epic - do not delete

#### User Story

As a security engineer or analysts
I want to have clear documentation
To use this awesome new functionality

#### Acceptance Criteria

- If a user goes to the docs, they are able to find a page or a section explaining this feature
- If a user finds the docs, they should get a high-level overview followed by a detailed explanation of how this feature works, including arguments, options, caveats, considerations, and tips

**Comment by jacknagz** [comment]
@nhakmiller @mattthetraveler Updated this Epic. When we do the RFC, we'll have to decide on how to break this feature up into MVP/MMP/MDP. I don't have enough insight today to do that.
