### ISSUE TITLE
Log Analysis initial Metrics 

### ISSUE THREAD

**Issue by alexmylonas** [panther-labs/panther#1125]
As a user, i want to see high level analytics about the **Events** ingestion from sources and **Alerts** generated by the rules that i have enabled.

More specifically I want to see: 
 
**1. A quick overview of alerts progression week by week:**

![Screenshot 2020-07-06 at 8.44.20 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/99280f40-6147-46c0-876c-0b99c8656b4a)

**2. An overview of last week's Alerts by severity:**

![Screenshot 2020-07-06 at 8.47.03 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/6e822625-55be-4fb6-b6da-9731487553bf) 

**3. An overview of last week's Events by Log type:**

![Screenshot 2020-07-06 at 8.49.11 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/2916e412-0534-4ad7-bd1b-75ab4438bcbd)

All these should aligned with this preview: 

![Screenshot 2020-07-06 at 8.51.27 PM.png](https://images.zenhubusercontent.com/5e4fb724a541ae524a4864cc/9084fffd-3661-4dab-a0a0-32e4c6125574)

This is the MVP of #955 and includes both backend and frontend work necessary.

Backend: 

- [ ] should make sure we have all this info available.
- [ ] expose endpoint(s) that return all necessary data for aforementioned graphs

Frontend:  
- [ ] should fetch necessary data for the graphs
- [ ] display `Total Alerts` card
- [ ] display `Alerts by Severity` graph
- [ ] display `Events by Log type` graph
- [ ] display `Recent Alerts/High Severity Alerts` table

Notes: Not allowing users to "free" select past dates and display just last week analysis is deemed viable but could be considered a stretch goal.
