### ISSUE TITLE
Detection Packs [MVP]

### ISSUE THREAD

**Issue by wey-chiang** [panther-labs/panther#1728]
> **_Note:_** This is the main Epic. There may be sub-epics to track the phases of feature completion.

## Description

Currently, users lack the ability to automatically manage the various rules that Panther has to offer. Furthermore, manual action is required from users every time a new rule package comes out to receive these updates. As a result, we impose the burden on users by requiring them to watch for panther release notes to keep up with the latest and greatest.

The goal of this feature is to automate the whole process and allow users to "button-click" to update their detections. This will allow the Panther team to better manage and roll-out changes to all its customers.

## RFC

[RFC](https://github.com/panther-labs/panther-enterprise/blob/master/designs/security/simplify-detection-management/README.md)

## Design

[Designs](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/e13b9697-49e3-498c-8b21-e21c20458cc5)

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @wey-chiang @lindsey-w 
- [X] Frontend assigned [frontend] @alexmylonas 
- [x] Designs mocked [designer] @dimitriszoitas 
- [x] Stories planned [fe/be] @lindsey-w @alexmylonas 
- [ ] Stories executed [fe/be] @lindsey-w @alexmylonas 
- [ ] Validation [product/feature owner] @mattthetraveler 

---

# Stories and Criteria

### User Stories

As an analyst,
I want the ability to view Detection Packs in the Panther UI and download new packs when new useful packs become available.

### Acceptance Criteria

- Display a page dedicated to listing and filtering available packs
- Each pack should have metadata including versions, types, descriptions, and names
- I should be able to view new Detection Packs to download in an update within the Panther UI
- When packs are downloaded, there is a verification of authenticity to ensure no tampering has occurred
   - For rule developers, there should be a manifest file that describes the pack with its detections

---

### User Stories

As an analyst
I want to be able to delete detection packs I no longer need, disable detection packs that I want to pause, and enable them again in the future

### Acceptance Criteria

- add function to enable detection packs from the UI
- add function to disable detection packs from the UI

---

### User Stories

As an analyst
I want to be able to update all detections within a pack without having to individual update each detection.

### Acceptance Criteria

- When an action is taken on a pack, it should apply to all related detections

### User Story

As an analyst
I want to be able to group detections together to form a new detection pack
So I can distribute multiple detections easily

### Acceptance Criteria

- Packs can be created as a group of detections
  - Potentially using a set of filters/queries or specific Detection IDs
  - Packs must have an associated version to support rollbacks

---

### User Stories

As an analyst,
I want to learn how I can download new packs into Panther and also create my own

### Acceptance Criteria

- "Detection Pack" sub-tab in documentation under Writing Detections
- Detailed instructions on how to perform key workflows with Detection Packs

**Comment by mattthetraveler** [comment]
Hi @wey-chiang , are there any issues closed/in progress/ to do that we can associate with this Epic?

**Comment by jacknagz** [comment]
@lindsey-w could you please set the estimated start/end date for this epic so @mattthetraveler and I understand when it's planning to complete? Also, are all of the subtask assignees set?

**Comment by lindsey-w** [comment]
@jacknagz I added milestones to the subtasks and a release to the epic itself.  I'll work with @mattthetraveler on getting the design and FE subtasks included here. 
The BE work should be done by the end of the next sprint - finished the RFC discussion and started implementation this sprint.

**Comment by lindsey-w** [comment]
> - Users should be able to enable, disable, update, or delete the detection packs

I'm unsure what "delete" action on a pack will really do - since a new polling action will simply re-add it to the database (but in a `disabled` state). That said, a `delete` might help with cleanup of old/deprecated packs. This is an outstanding topic/question I have, and I don't think that endpoint will be in v1

> - Users can configure a URL to pull packs down from

User configurability not in v1

**Comment by jacknagz** [comment]
@lindsey-w updated
