### ISSUE TITLE
Mocking Support in Detections [MVP]

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther#1744]
## Description

Currently, Panther detections that make external API calls cannot be unit tested, which has led to workarounds or lack of test coverage.  Adding support for mocking will allow us to more fully support unit testing in generic rule/policy logic and will provide more confidence in detections that make external calls.

## RFC

[RFC](https://github.com/panther-labs/panther-enterprise/pull/967/files)

## Design

In-Progress

## Status and Stakeholders

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @wey-chiang 
- [x] Frontend assigned [frontend] @vorillaz 
- [ ] Designs mocked [designer] @dimitriszoitas 
- [ ] Stories planned [fe/be] @wey-chiang @vorillaz 
- [ ] Stories executed [fe/be] @wey-chiang @vorillaz 
- [ ] Validation [product/feature owner] @mattthetraveler 

# Stories and Acceptance Criteria

### User Story

As an analyst
I want to have the ability to mock API calls in the Panther CLI
so I can test out the efficacy of the detection I write

### Acceptance Criteria

- Users should be able to add mock definitions in the detection YML files via the CLI
- Users can use `panther_analysis_tool` to properly run tests using mocked object

### User Story

As an analyst
I want to have the ability to mock API calls in the Panther UI
so I can test out the efficacy of the detection I write

### Acceptance Criteria

- In the test record section of the "edit" policy/rule pages, add ability to "add Mock" to an individual test record
  - When this is selected, the user should be able to select from existing mocks or add a new mock (perhaps in a pop up screen or a dropdown)
  - When user adds a new mock, they should be able to define the following fields and then hit "Apply":
    - mock function name (in Python)
    - desired return value (in Python)

### User Story

As an analyst
I want clear documentation that shows me how to use unit test mocking
so I can start writing better detections

### Acceptance Criteria

- Base documentation on how to set up a mock in the "Writing Detections" section of our documentation
  - We should use actual examples of how a user would mock an API call

**Comment by jacknagz** [comment]
FYI: I've updated the acceptance criteria

**Comment by nhakmiller** [comment]
Updated the milestone to next sprint as we've re-arranged the oncall rotation so Weyland is on call this sprint.

**Comment by mattthetraveler** [comment]
FYI @vorillaz this will likely be prioritized in the next sprint. Make sure you review the epic/RFC and provide feedback if you need more context

**Comment by mattthetraveler** [comment]
Hi @austinbyers could you take a look at the scope/objectives of this epic? Is there any insight you have to make this a more impactful feature?

**Comment by austinbyers** [comment]
I don't have any specific context here, this would be the domain of the @panther-labs/security-engineering team.

> I want to have the ability to mock API calls

This is an accurate objective - analysis write python that talks to external services but don't have an easy way to test that python without triggering the live request.

**Comment by wey-chiang** [comment]
PR for the BE implementation:

https://github.com/panther-labs/panther/pull/2628
