### ISSUE TITLE
Bulk change alert statuses

### ISSUE THREAD

**Issue by s0l0ist** [panther-labs/panther#1810]
### Description

Individually changing each alert's status is tedious and cumbersome, especially when writing a test rule and later going back to update the status of the alerts.

The current backend Alerts API allows for updating a single alert. This needs to be extended to allow for multiple alerts.

### RFC

No explicit link. This epic is rather small and it will address the following:
- [x] Backend API needs to accommodate multiple AlertIDs
  - [x] Needs to use DDB transactions in case of failure
  - [x] Needs to process data in parallel as DDB has an upper limit for transaction items (25).
- [ ] Frontend changes

### Designs

The [link](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/collections/0e79571a-428a-4c7f-bb8d-f6c4e457eb57) to the feature's designs

### Acceptance Criteria

**Any** view that displays/lists **multiple** alerts needs to have the ability to check multiple alerts via a checkbox (or all on the page) and bulk and set their status (Open, Triaged, Ignored, Resolved).

A user should be able to click the checkboxes for a list of alerts.

For example:

- User views a list of alerts
- User sees there's an option to change the alert's status
- User can either update a single alert's status the way it currently exists
- User also sees the ability to check multiple alerts
- User can scroll and click multiple alerts and change their status
- User can also click a button to select all the alerts on the page, pick status for all of them which can be saved on status selection or from a separate 'submit' button.
  - Ex: user wants to change all `INFO` alerts to `Resolved` he can filter, check all with one click, and set the status.

**Comment by jacknagz** [comment]
The updated design link should [be this](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/collections/0e79571a-428a-4c7f-bb8d-f6c4e457eb57)

**Comment by jacknagz** [comment]
FYI - When the frontend is ready, please ping me or @mattthetraveler for final review (cc @alexmylonas ) Thanks!
