### ISSUE TITLE
Configurable Cloud Security Scanning [MVP]

### ISSUE THREAD

**Issue by nhakmiller** [panther-labs/panther#1979]
## Description

The Cloud Security scanning system is fairly generic, and intended to work in most cases for the most uses. However, this sometimes falls apart for specific environments/use cases where these general assumptions are wrong.

Users should have more configuration options for Cloud Security scanning, similar to how Log Analysis has several configuration options (e.g. using KMS keys, using prefixes, using SQS/S3, etc). Specifically, we've had requests for the following configuration options:

- Specifying which regions should/should not be scanned to align with Organization SCPs that block all actions in certain regions
- Specifying which resource types should/should not be scanned for certain sources

These settings should be configurable when onboarding new sources.

## RFC

N/A

## Design

Designs are [here](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/0d293ff7-a6c6-4ddc-9dd0-442c63b91995/commits/b61b921be3b17ee62e31623cc0c77f6eee24f17c/files/323d0ca1-81a8-40e7-83ee-0a05b870bb4a/layers/E41DFB1E-102D-4DDC-9EBB-1D8973CEE5C2?mode=design&sha=b61b921be3b17ee62e31623cc0c77f6eee24f17c)

## Status

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner]
- [x] Designs mocked [designer] @dimitriszoitas 
- [x] Stories planned [fe/be] @wey-chiang 
- [x] Stories executed [fe/be] @wey-chiang 
- [ ] Validation [product/feature owner] @mattthetraveler 

# Stories and Criteria

### User Story

As a user
I want to disable cloud scanning for certain resource types

Example:

1. A user has a Cloud Security source enabled, and the source has no restrictions.
2. The user notices that a large number of scans of AWS ELBV2 Load Balancers are getting rate limited, causing issues in production
3. The user logs in to Panther and goes to the Cloud Security sources page to modify this source
4. The user clicks edit source and specifies that AWS ELBV2 Load Balancers resources should not be scanned
5. The backend respects this configuration and ELBv2 load balancers are skipped for all scans on this source

### Acceptance Criteria

- Enable ability to disable cloud scanning for resource types in the cloud security onboarding experience
- Enable ability to disable cloud scanning for resource types in source editing page (post-onboarding)

### User Story

As a user
I want to disable cloud scanning for certain AWS regions

Example:

1. User wants to add a new Cloud Security source, so they go to the Cloud Security Add Source page and start the wizard
2. The user knows that they don't want to scan any `eu` region because they have these regions disabled via SCPs, so they configure the source to ignore all  `eu` regions while scanning.
3. The user saves the source, their source specific configurations being saved
4. The backend respects these configurations and so the user's account is not scanned in the `eu` regions

### Acceptance Criteria

- Enable ability to disable cloud scanning for regions in the cloud security onboarding experience
- Enable ability to disable cloud scanning for regions in source editing page (post-onboarding)

### User Story

As a user
I want to disable cloud scanning for resources with a certain prefix or naming convention

Example:

1. User wants to add a new Cloud Security source, so they go to the Cloud Security Add Source page and start the wizard
2. The user knows that they don't want to scan any resources with the name "panther-rules-" because they have those specific resources disabled via SCPs, so they configure the source to ignore all resources with "panther-rules-` prefixes while scanning.
3. The user saves the source, their source specific configurations being saved
4. The backend respects these configurations and so the user's account is not scanned for "panther-rules-" prefixes.

### Acceptance Criteria

- Enable ability to disable cloud scanning for resources with certain naming conventions through a glob matching field in the UI
- Enable ability to disable cloud scanning for resources with certain naming conventions in source editing page (post-onboarding)

**Comment by nhakmiller** [comment]
Bumping  this to a `p0` priority  as we have observed the following scenarios a few times:

- One particular resource type scan is failing
- This failure is so noisy/disruptive in nature that user is forced to turn off entire Cloud Security feature

Being able to just disable the noisy region or resource type would allow end users to still make use of the Cloud Security feature even in the face of disruptive partial failures.

**Comment by wey-chiang** [comment]
I have a PR for the BE support for this out, @3nvi are we good for the v1.16 release?

**Comment by 3nvi** [comment]
Sorry for the late reply @wey-chiang , was waiting to get the latest priorities. According to what we aim to release in 1.16, this may  or may  not make the cut, since we already have 3 big features to deliver.

I'm fully ok bumping it higher in terms of priority, but I think that this won't align with the company's priorities

cc @mattthetraveler

**Comment by nhakmiller** [comment]
We really want to get the backend component in ASAP because a few specific customers needed the change, but we can work with them to manually tweak the DynamoDB entries for now with the configurations they need and the FE can come later if there is not room for it next sprint (already confirmed with the customers in question that they would be ok with that for now).

**Comment by 3nvi** [comment]
Thanks for the update. As it stands there's a 70-75% chance this will be picked up, but I can't guarantee it 😞

**Comment by wey-chiang** [comment]
@mattthetraveler I left some comments on Abstract but for the most part, the MVP for this epic is completed & ready for verification

**Comment by mattthetraveler** [comment]
@wey-chiang awesome. Let's kick the tires on this in dogfooding and close out afterwards

**Comment by wey-chiang** [comment]
Issue cloned.
