### ISSUE TITLE
System Health Notifications [MVP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2199]
## Description

In order to determine if logs are continually flowing and alerts are being received, users need to perform manual checks to make sure the log ingestion pipeline is working and that data is being pulled, analyzed, stored, and dispatched through various destinations. Currently, in the UI, there are a number of pages that give statuses, such as the log sources page, which shows healthy/unhealthy data sources, but this requires the user to reactively investigate whether the source has become unhealthy.

The purpose of this feature is to provide a holistic and proactive system that notifies users as soon as any part of this critical pipeline breaks.

## RFC

[RFC](https://github.com/panther-labs/panther-enterprise/blob/master/designs/data_processing/system-status/README.md)

## Design

> **_Note:_** In each sub-epic

## Status and Stakeholders

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @kostaspap 
- [x] Frontend assigned [frontend] N/A
- [ ] Designs mocked [designer] N/A
- [ ] Stories planned [fe/be] @kostaspap 
- [ ] Stories executed [fe/be] @kostaspap 
- [ ] Validation [product/feature owner] @mattthetraveler @kostaspap 

---

# Stories and Criteria

### User Story

As a user
I want to configure the system notification destinations
When checking an option on the Destinations onboarding page

### Acceptance Criteria

Users can navigate to the Settings > Destinations page and select a new alert type called "System Health" as an option in the current/new destinations to receive System Health alerts.

When users receive alerts from System Health, they contain a link in the UI where they can view more information and understand the errors returned from each service. 
  - For example, if a source is unhealthy, it will link to the integrations page, or if an alert cannot be delivered to a destination, it will link to the alert overview page. 
  - There should be enough information in the alert for the system operator to understand what the problem is.

---

### User Story

As a security engineer
I want to receive a system notification 
If any of my data sources become unhealthy
So I can make sure monitoring is always on

### Acceptance Criteria

- A notification is generated when cloud security accounts, log sources, or SaaS sources become unhealthy
- When the notification is received, it contains enough information to understand what broke, including the name of the source and its type

---

### User Story

As a security engineer
I want to receive a system notification 
When my data source volume significantly decreases
So I am not dropping data or disrupting my monitoring

### Acceptance Criteria

- A notification is generated when cloud security, logs, or SaaS sources completely drop off from sending data
- A notification is generated when cloud security, logs, or SaaS data volumes fall outside of the expected range for a given log source

---

#### User Story

As a security engineer
I want clear documentation on how our System Health system works
So I can confident that the alerts I'm getting are actually meaningful

#### Acceptance Criteria

- Users should be able to understand how they can configure and adjust destination settings for System Health notifications
- Users should be able to view a diagram of how the System Health system works and notifies users

**Comment by 3nvi** [comment]
Marking as p1 since it's gonna be picked up in the next quarter

**Comment by kostaspap** [comment]
Hello @mattthetraveler, some notes: 

* I think that `Data Source Health [MVP]` should actually be split to two different MVPs, one for log sources (SaaS/SQS/S3/etc it doesn't really matter) and another for Cloud Security. These two products work in a very different way, have different requirements and will require a different approach. 
* `Log Source Health [MVP]` should be its own epic, it is really hard to keep track of everything in one master epic (this one). 
* `System Settings [MVP]` has overlap with `Log Source Health[MVP]`. We cannot notify the user if a failing log source if they haven't configured how they want to be notified. 
* Regarding the `Data Source Health[MVP]` acceptance criteria: The criteria `A notification is generated when data sources become unhealthy` is very vague - it is actually a very hard problem to identify when a source is unhealthy. My understanding from the last discussion we had was that we would let users define a lower threshold of events processed per LogType or per Source. We could also ask them for a period so they can configure something like "notify me if the # of events processed for LogType XYZ are below N over a period of M minutes". What we would need from product is define if the configuration should be per source, per log type (I am in favor of the latter).

**Comment by mattthetraveler** [comment]
Hi @kostaspap 

> I think that Data Source Health [MVP] should actually be split to two different MVPs, one for log sources (SaaS/SQS/S3/etc it doesn't really matter) and another for Cloud Security. These two products work in a very different way, have different requirements and will require a different approach.

This makes sense. I'll separate that out in the description. For MVP, we should focus on Log Sources over Cloud Security resources.

> Log Source Health [MVP] should be its own epic, it is really hard to keep track of everything in one master epic (this one).

I can reactivate the [old nested epic ](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2559) and we can use that to track MVP progress. You can open issues under that.

> System Settings [MVP] has overlap with Log Source Health[MVP]. We cannot notify the user for a failing log source if they haven't configured how they want to be notified.

Yes this is part of MVP, Log source health notifications is dependent on it. Let's roll this into the above mentioned nested epic.

> Regarding the Data Source Health[MVP] acceptance criteria: The criteria A notification is generated when data sources become unhealthy is vague - it is actually a very hard problem to identify on Panther side when a source is unhealthy and when it is healthy. 

This is just referring to the current health check we perform on log sources/cloud security sources. We should generate a notification when the source becomes unhealthy via the existing health checks we do today.

> My understanding from the last discussion we had was that we would let users define a lower threshold of events processed per LogType or per Source. We could also ask them for a period so they can configure something like "notify me if the # of events processed for LogType XYZ are below N over a period of M minutes". What we would need from product team is define if the configuration should be per source or per log type (I am in favor of the latter).

Yes we want to include this in MVP as well (notifications for log volumes), in addition to notifications for sources that turn unhealthy and that completely drop off. And based on customer feedback, configuring this by log source would be ideal

**Comment by mattthetraveler** [comment]
Old implementation notes:

System Status API:
   - Looks up CW Alarms to see the status of a component. In case it is in error, queries DDB to get last error message reported by that system. This could mean that only the latest error reported by a particular component will be returned to the user.
   - Listens to new messages from the SQS queue:
      - Log Success/Failure metrics in CW Logs
      - In case of failure, it stores the error message in DDB
   - System Alerts Notification: New Lambda that listens for any CW Alarms firing in the system. It can forward a notification downstream to destinations

**Comment by jacknagz** [comment]
FYI @kostaspap we have updated the main acceptance criteria in this issue and have opened an MVP Epic [here](https://github.com/panther-labs/panther/issues/2559)

**Comment by kostaspap** [comment]
@jacknagz @mattthetraveler  I don't think it makes sense to have design as part of this epic. 
Each epic should have its own designs imo that @dimitriszoitas should pick when we pick each epic. I am afraid we will end up having a big design for this epic, but no individual designs for each of the MVPs

**Comment by mattthetraveler** [comment]
@kostaspap agreed. Status will be moved to sub-epics and we'll iterate on designs there
