### ISSUE TITLE
Unified Overview [MVP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2244]
## Description

The purpose of the Unified Overview is to provide a single page for all dashboards in Panther. The dashboards are designed to provide awareness about alerts, detections, data, and system health. Currently, these graphs are spread out across several overview pages, but as we introduce more features related to data analysis we need to avoid creating yet another overview page. This change proposes bringing all of them together into a single page separated by tabs.

## RFC

[RFC](https://panther-labs.atlassian.net/wiki/spaces/EN/pages/720207938/RFC+Simplify+the+UI)

## Design

> **_Note:_** To be updated by the feature owner once completed

## Status and Stakeholders

> **_Note_**: Tag each responsible party below

- [x]  Epic created [@jacknagz]
- [x]  RFC written [@jacknagz]
- [x]  Frontend assigned [@3nvi]
- [x]  Backend assigned [N/A]
- [x]  Designs mocked [@dimitriszoitas]
- [ ]  Stories planned [@3nvi]
- [ ]  Stories executed [@3nvi]
- [ ]  Validation [@jacknagz]

---

#### User Story

As an analyst
I want a summary of my Panther Alerts
In an Overview page Alerts tab
To understand the high-level activity of my detections and their response

#### Acceptance Criteria

- If Analyst navigates to the webpage Overview, they see a tab for Alerts with several graphs
- The total number of alerts within the selected time period is shown as a number, with the differential summary provided below, as is, today
- The total number of alerts is graphed by severity on a line chart, as is, today
- The most active detections are displayed as a horizontal bar chart, as is, today
- 5 "High Priority Alerts" [in the open state + created in the last 24 hours] are listed as cards

---

#### User Story

As an analyst
I want to understand the overall status of my cloud resources and policies
In the Overview page's Cloud Security tab
To get a basic understanding of how good or bad things are

#### Acceptance Criteria

- A "Resource Status" chart displays two colors, green (passing) and red (failing) showing compliance or non-compliance with the running policies. 
- The "Resource Status" also shows the total count of all resources
- When clicking one of the "Resource Status" colors, the user is taken to the resources page with the appropriate filters in place (filtering to the passing or failing resources)
- A "Policy Fail Breakdown" vertical bar chart shows the breakdown of policies by severity
- When clicking one of the "Policy Fail Breakdown" colors, the user is taken to the detections page with the appropriate filters in place (filtering on detection type of policy and status of failing)
- The 5 Top Failing Resources are listed below the "Resource Status" chart with an infobox explaining how we define what a "top failing resource" is
- The 5 Top Failing Policies are listed below the "Policy Status" chart with an info box explaining how we define what a "top failing policy" is

---

#### User Story

As an engineer of the system
I want to understand the incoming log volume
In the Overview page's Data tab
To observe data spikes, drops, and general throughput

#### Acceptance Criteria

- A "Number of Events by Type" chart is displayed as a line graph showing the total number of events by log type (the same chart that exists today in the Log Analysis -> Overview page

---

#### User Story

As an engineer of the system
I want to understand the delay between logs originating and entering Panther
In the Overview page's Data tab
To gain operational awareness that detections may be running against older data

#### Acceptance Criteria

- A "Data Latency" bar chart is displayed as an average latency by log type, for the filtered time period
- The units will be displayed as minutes, rounding to the nearest 2 decimal places (there may be some with less than a minute)

---

### Documentation

> **_Note:_** This is a requirement for every Epic - do not delete

#### User Story

As a security engineer or analysts
I want to have clear documentation
To use this awesome new functionality

#### Acceptance Criteria

- If a user goes to the docs, they are able to find a page or a section explaining the available dashboards and what they mean

**Comment by jacknagz** [comment]
I believe this should also be addressing the frontend for the Ops Notifications/Statuses, right @kostaspap @mattthetraveler ?

**Comment by mattthetraveler** [comment]
That's correct @jacknagz . FYI @dimitriszoitas , per our previous discussions on scoping down the System Health status/ Ops notification design [work here](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther-enterprise/1533)

**Comment by jacknagz** [comment]
@mattthetraveler @3nvi @dimitriszoitas 

As you can see, this ticket has been overhauled to break this Epic into 3 phases. 

I've created an MVP epic that tracks the stories and criteria we want to tackle first.

@3nvi please sign-off on the stories/criteria before we kick it over to design

**Comment by jacknagz** [comment]
You'll also notice that the System Notifications tab is not in here. It's been moved to the [System Health Notifications](https://app.zenhub.com/workspaces/panther-5e4f99c4fbfd0c5803686679/issues/panther-labs/panther/2199) MDP, instead (FYI @kostaspap)

**Comment by jacknagz** [comment]
Once we move past the MVP phase, I'll need assistance from a member of security engineering (FYI @nhakmiller). Once planning comes around in one of the following sprints, we can take this work.

**Comment by 3nvi** [comment]
All looks good

**Comment by nhakmiller** [comment]
> Once we move past the MVP phase, I'll need assistance from a member of security engineering (FYI @nhakmiller). Once planning comes around in one of the following sprints, we can take this work.

Sounds good, as we get ready to implement I'll tag somebody.

**Comment by nhakmiller** [comment]
> Average Data Latency

It sounds like the difference between this and the current graph is that the current graph shows multiple data points in a time series data format and you want a single data point for a given time period? That should be doable, it's possible today by just setting the interval equal to the time period but we can also add a dedicated endpoint that gets this data point.

**Comment by jacknagz** [comment]
> the current graph shows multiple data points in a time series data format and you want a single data point for a given time period?

Correct

> it's possible today by just setting the interval equal to the time period but we can also add a dedicated endpoint that gets this data point.

Does the frontend have to calculate the average if we were to just keep with the current implementation?

**Comment by nhakmiller** [comment]
> Does the frontend have to calculate the average if we were to just keep with the current implementation? @nhakmiller

The frontend gets to specify both the period of time in consideration, and how long each interval in that time period is. So if they ask for a two week time period, and request a two week interval, they will get back one number which is the average for that two weeks.

But it would be simple API work to add an endpoint that only accepts a time period and just gives the average for that time period, I was just saying if the FE ends up blocked by this then they have options.
