### ISSUE TITLE
Upgrade AWS Go SDK to v2

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#2467]
### Description

AWS Go SDK v2 is now [generally available](https://aws.amazon.com/about-aws/whats-new/2021/01/aws-sdk-for-go-version-2-now-generally-available/)!

There are substantial performance improvements in the new library (which, in turn, lead to cost savings), so it's definitely worth our time to switch sooner than later. We'll wait a few weeks for them to patch any issues before we start upgrading Panther services. The upgrade need not happen all at once - each service owner can migrate their own service when they have a few spare cycles to do so.

This epic is not necessarily anyone's dedicated responsibility yet; it's just a convenient place to track which services have been upgraded and any roadblocks we encounter along the way.

See [migration docs](https://aws.github.io/aws-sdk-go-v2/docs/migrating/)

### Acceptance Criteria

- Eventually, all aws go sdk imports are switched to `github.com/aws/aws-sdk-go-v2`

Check off each service once the migration is complete:

#### `cmd`

- [ ] `devtools`
- [ ] `opstools`

#### `internal/compliance`

- [ ] `alert-forwarder`
- [ ] `alert-processor`
- [ ] `aws-event-processor`
- [ ] `compliance-api`
- [ ] `datalake-forwarder`
- [ ] `remediation-api`
- [ ] `remediation-processor`
- [ ] `resources-api`
- [ ] `snapshot-poller`
- [ ] `snapshot-scheduler`

#### `internal/core`

- [ ] `alert-delivery`
- [ ] `analysis-api`
- [ ] `custom-resources`
- [ ] `database-api` (enterprise)
- [ ] `layer-manager`
- [ ] `logtypesapi`
- [ ] `metrics-api`
- [ ] `organization-api`
- [ ] `outputs-api`
- [ ] `source-api`
- [ ] `users-api`

#### `internal/log-analysis`

- [ ] `alert-forwarder`
- [ ] `alerts-api`
- [ ] `datacatalog-compactor` (enterprise)
- [ ] `datacatalog-compactor-reaper` (enterprise)
- [ ] `datacatalog-updater`
- [ ] `log-processor`
- [ ] `log-puller` (enterprise)
- [ ] `message-forwarder`

#### `pkg`

- [ ] `awsathena`
- [ ] `awsbatch`
- [ ] `awscfn`
- [ ] `awscostexplorer`
- [ ] `awsretry`
- [ ] `awssqs`
- [ ] `awsutils`
- [x] `box` (N/A)
- [ ] `encryption`
- [x] `extract` (N/A)
- [ ] `gatewayapi`
- [ ] `genericapi`
- [x] `lambdalogger` (N/A)
- [x] `metrics` (N/A)
- [x] `oplog`(N/A)
- [x] `priorityq` (N/A)
- [x] `prompt` (N/A)
- [x] `shutil` (N/A)
- [x] `stringset` (N/A)
- [ ] `testutils`
- [x] `unbox` (N/A)
- [ ] `x`

#### `tools`

- [ ] `mage`

**Comment by alxarch** [comment]
Going through the migration docs. It seems that there are some substantial changes.
I find it good that creating a session requires a `context.Context` and also that Options use the [functional option idiom](https://www.sohamkamani.com/golang/options-pattern/).

One area that will be tricky to migrate will be the `CredentialProvider` changes. These will mostly affect S3-related services where Panther has to be using multiple S3 clients with different credentials depending on the bucket it wants to read from.
 
FIPS compatibility relies on shared sessions across all AWS clients. This will probably enforce moving full Lambdas at once. Make sure to check your changes with enterprise *before* merging on oss to avoid backports.

It would be good to have an 'example' migration first to iron out details in the process before everyone goes on to migrate their components independently. It won't make sense to be solving that same problem over and over, and it will keep the code somewhat coordinated if we all do the migration in a similar fashion.

**Comment by alxarch** [comment]
Looking through the code for some services in v2 (dynamodb), it seems all client methods now *require* `context.Context`. This will mean we'll have to update mocks and tests as well.

**Comment by austinbyers** [comment]
Since we want epics to have one assignee, just adding myself for now.

`mage` will likely be the first to switch to the new SDK since it's only dev tooling and not part of Panther itself
