### ISSUE TITLE
Declaring YAML Schemas [MVP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2525]
## Description

Our current management of 'native' log types is bound to the releases of Panther itself. We want to manage our schemas in the same way we manage our rules, in a repository. This feature will help us transition to defining and managing schemas in an independent repository and which issues must be solved in the log processing pipeline and data catalog updater components to achieve that.

As an analyst, I want to manage my schemas in the same way I manage my rules, in a repository.

## RFC

[RFC](https://github.com/panther-labs/panther-enterprise/blob/e16ecb2ff8d6b099e88f88395a2864f4aaee2106/designs/data_processing/managed_schemas/README.md)

## Designs

N/A

## Status

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @alxarch 
- [x] Stories planned [fe/be] @alxarch 
- [x] Stories executed [fe/be] @alxarch 
- [ ] Validation [product/feature owner] @mattthetraveler 

# Stories and Criteria

### User Story

As an analyst, 
I want to view Panther-created schemas in a public repository that I can use in the Panther UI
So I don't have to write my own

### Acceptance Criteria

- User should be able to find Panther-created schemas in a public facing repository that they can upload in the Panther UI

**Comment by kostaspap** [comment]
@mattthetraveler The acceptance criteria don't seem correct? E.g.

> User can define YAML schemas in the Panther UI in the Custom Schemas page
This is already available in the product

> User can define YAML schemas from a repo

This is a bit unclear? What we want to support is that users should be able to update the schemas of their Panther deployment with the latest schemas available in the repo. 


> User can view, update, and manage YAML schemas in Panther UI

This is a bit broad... 

I think the acceptance criteria need to be more specific to differentiate between Panther-managed schemas and custom schemas created/updated/deleted by the users.

**Comment by mattthetraveler** [comment]
@kostaspap apologies, left it as a placeholder yesterday as I got more context on this. I updated the acceptance criteria with what was in the RFC. Let's discuss tomorrow what's containable in this sprint and break this up into more issues as needed. Also need to discuss FE/Design work so @3nvi can plan appropriately
