### ISSUE TITLE
Detection Packs [MMP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2575]
# Description

As an analyst using Detection Packs, I want to have more control over detection packs and more easily onboard new panther-managed detection packs. This will make the onboarding experience much more seamless and will also make detection management simpler. 

# RFC

[RFC](https://github.com/panther-labs/panther-enterprise/blob/master/designs/security/simplify-detection-management/README.md)

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @wey-chiang @lindsey-w 
- [x] Frontend assigned [frontend] @alexmylonas 
- [ ] Designs mocked [designer] @dimitriszoitas 
- [ ] Stories planned [fe/be] @lindsey-w @alexmylonas 
- [ ] Stories executed [fe/be] @lindsey-w @alexmylonas 
- [ ] Validation [product/feature owner] @mattthetraveler 

# Stories and Criteria

### User Story

As a security engineer
I want to specify an additional location for my Detection Pack(s) in GitHub
So I can write my own (private) Packs to supplement Panther Labs' built-in Packs

### Acceptance Criteria

- User can add additional pack sources in the Settings > General page in a new box called "Detection Pack Sources"
  - Metadata: Display Name, URL, signature filename, public key for signing key
- user can edit a new pack source in the UI
- user can delete a pack source in the UI
  - this also deletes the packs associated with the source

---

### User Story

As an analyst
I want to be able to sort Detections by Pack on the List Detections Page
To see the associated Detections with a Pack

### Acceptance Criteria

- On the List Detections page, there is a "Detection Pack" filter to sort by which will show all associated Detections

--- 

### User Stories

As an analyst,
I want a detection pack dedicated to critical AWS-related detections
That provide high-value alerts and low noise

### Acceptance Criteria

- Scrub existing default detections of least-impactful alerts (less is more)
- New detection pack with critical AWS detections that are selected at the discretion of the Sec Eng Team

---

### User Stories

As an analyst,
I want to learn how I can interact with Detection Packs
To use this awesome new feature :)

### Acceptance Criteria

- Review "Detection Pack" documentation and update with new features
