### ISSUE TITLE
Unified Integrations Page [MVP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2576]
## Description

To keep with the theme of unification, we should consolidate all pages related to external integrations into one tab with 3 sub-tabs: Alert Destinations, Log Sources, and Cloud Accounts.

In addition to consolidation, we should expand our Log Sources experience to display all of log sources we support in Panther today, similar to our external integrations page.

## RFC

[RFC](https://panther-labs.atlassian.net/wiki/spaces/EN/pages/720207938/RFC+Simplify+the+UI)

## Design

- [Accounts](https://share.goabstract.com/96a7b795-f26c-433a-b567-12ed553fa8ce)
- [Alert Destinations](https://share.goabstract.com/f8389484-d590-419e-8fa2-9b8bb8f599ca)
- [Log Sources](https://share.goabstract.com/dbf178c4-c6fa-4a20-9646-6d95d07de6db)

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @jacknagz 
- [x] Frontend assigned [frontend] @3nvi 
- [x] Designs mocked [designer] @dimitriszoitas 
- [ ] Stories planned [fe/be] @3nvi 
- [ ] Stories executed [fe/be] @3nvi 
- [ ] Validation [product/feature owner] @mattthetraveler 

# Stories and Criteria

### User Stories

As a security engineer
I want to view, manage, add, and delete to my connected AWS accounts in the Panther UI
To initiate Cloud Security scans

### Acceptance Criteria
- As a user, I should be able to view "Cloud Accounts" in the new "Integrations" tab
- User can view connected AWS accounts in the Integrations tab in the "Cloud Accounts" sub-tab
- User can manage connected AWS account in the "Cloud Accounts" sub-tab

---

### User Story

As a security engineer
When adding a new log source
I want to see all of the supported log types in a single window
To understand all the possible types of data I can analyze

### Acceptance Criteria

- As a user, I should be able to view my log sources in a "Log Sources" sub-tab in the "Integrations" tab
- Rename to "Log Sources"
- Maintain existing "Sources" view page where user can see all SaaS Log Pullers and Data Transports

In Log Source onboarding experience:

**SaaS Log Pullers**
  - Reuse tiles that exist in the current "Sources" onboarding experience
  - Reuse existing onboarding experience for each SaaS Log Puller (once you click on the tile, you're dropped into the onboarding flow)
  - SaaS Log Pullers should have an "Enterprise" tag

**Supported Log Sources**
  - Create new tiles for all of the log sources that panther supports today, similar to the external integrations page we have today
  - In the details page for each log source, the tile displays App Info, Use Cases, and How it works copy from the external integrations page
  - The user should have the option of using S3, SQS, SNS, or Eventbridge as their Data Transport method in the details page
     - Clicking on one of these options should initiate the onboarding experience for that data transport

---

### User Stories

As a security engineer
I want to view, add, and manage configured destinations in the "Integrations" tab
so I can view my current configurations for alert delivery

### Acceptance Criteria

- As a user I should be able to find "Alert Destinations" in the "Integrations" tab
