### ISSUE TITLE
[MVP] Unified Overview

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther#2582]
> **_Note:_** This epic is used just for scoping and tracking purposes. For information on the stories tracked here, refer back to the original Epic.

# Stories Tracked

- Alerts Page Chart Migration [MVP]
- Cloud Security Chart Migration [MVP]
- Log Count by Type [MVP]
- Average Data Latency [MVP]
- Documentation [MVP]

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [x] Epic created [@jacknagz]
- [x] RFC written [@jacknagz]
- [x] Frontend assigned [@3nvi]
- [x] Backend assigned [N/A]
- [ ] Designs mocked [@dimitriszoitas]
- [ ] Stories planned [@3nvi]
- [ ] Stories executed [@3nvi]
- [ ] Validation [@jacknagz]

# Design

To be mocked

**Comment by 3nvi** [comment]
Hey @jacknagz , this [ticket](https://github.com/panther-labs/panther/issues/2492) removed the Data latency graph from the platform due to data/api bugs that were not able to quickly fixed. 

Should we remove it from the scope of this MVP?

**Comment by jacknagz** [comment]
Yep, I'll remove the data latency graph and allocate it into the MMP phase of this project

**Comment by jacknagz** [comment]
@3nvi I've updated this ticket - can you please coordinate designs and next steps?
