### ISSUE TITLE
Detection Packs

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2590]
> **_Note:_** This is the main Epic. There may be sub-epics to track the phases of feature completion.

## Description

Currently, users lack the ability to automatically manage the various rules that Panther has to offer. Furthermore, manual action is required from users every time a new rule package comes out to receive these updates. As a result, we impose the burden on users by requiring them to watch for panther release notes to keep up with the latest and greatest.

The goal of this feature is to automate the whole process and allow users to "button-click" to update their detections. This will allow the Panther team to better manage and roll-out changes to all its customers.

## RFC

> **_Note:_** To be updated by the feature owner once completed

[Here](https://github.com/panther-labs/panther-enterprise/blob/master/designs/security/simplify-detection-management/README.md)

## Design

> **_Note:_** To be updated by the feature owner once completed

[Here](https://app.abstract.com/projects/558a8de6-7134-4c8b-91c5-62074bb1279b/branches/df9d59c8-eeb1-452d-a5f5-3712b64010be/collections/e13b9697-49e3-498c-8b21-e21c20458cc5)

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @wey-chiang
- [X] Frontend assigned [frontend] @alexmylonas 
- [x] Designs mocked [designer] @dimitriszoitas 
- [x] Stories planned [fe/be] @wey-chiang
- [ ] Stories executed [fe/be]
- [ ] Validation [product/feature owner]

# Stories and Criteria

### User Stories

As an analyst,
I want the ability to view Detection Packs in the Panther UI and download new packs when new useful packs become available.

### Acceptance Criteria

- Display a page dedicated to listing and filtering available packs
- Each pack should have metadata including versions, types, descriptions, and names
- I should be able to view new Detection Packs to download in an update within the Panther UI
- When packs are downloaded, there is a verification of authenticity to ensure no tampering has occurred
   - For rule developers, there should be a manifest file that describes the pack with its detections

### User Stories

As an analyst
I want to be able to delete detection packs I no longer need, disable detection packs that I want to pause, and enable them again in the future

### Acceptance Criteria

- add function to enable detection packs from the UI
- add function to disable detection packs from the UI

### User Stories

As an analyst
I want to be able to update all detections within a pack without having to individual update each detection.

### Acceptance Criteria

- When an action is taken on a pack, it should apply to all related detections

## Documentation [MVP]

> **_Note:_** This is a requirement for every Epic - do not delete

#### User Story

As an analyst
I want clear documentation that shows me how to view, manage, create and download detection packs

#### Acceptance Criteria

- If a user goes to the docs, they are able to find a page or a section explaining this feature
- If a user finds the docs, they should get a high-level overview followed by a detailed explanation of how this feature works, including arguments, options, caveats, considerations, and tips

### User Stories

As an analyst
I want to be able to delete detection packs I no longer need

### Acceptance Criteria

- add function to delete detection packs from the UI

### User Stories

As an analyst
I want to input some basic configuration that can be stored and used to start polling for detection packs

### Acceptance Criteria

- user can add new pack sources in the UI
  - potential metadata: URL, signature filename, public key for signing key
- user can edit a new pack source in the UI
- user can delete a pack source in the UI
  - this also deletes the packs associated with the source

### User Stories

As an analyst
I want to be able to group detections together to form a new detection pack

### Acceptance Criteria

- Packs can be created as a group of detections
  - Potentially using a set of filters/queries or specific Detection IDs
  - Packs must have an associated version to support rollbacks

### User Stories

As an analyst
I want to be able to sort detection by pack in the detection overview page

### Acceptance Criteria

- add "detection pack" filter to detection list view page that allows sorting by detection name which is associated to a detection pack ID

### User Stories

As an analyst,
I want a detection pack dedicated to critical AWS-related detections

### Acceptance Criteria

- Scrub existing default detections of least-impactful alerts (less is more)
- New detection pack with critical AWS detections that are selected at the discretion of the Sec Eng Team

### User Stories

As an analyst,
I want to learn now I can download new packs onto Panther and also create my own

### Acceptance Criteria

- "Detection Pack" sub-tab in documentation under Writing Detections
- Detailed instructions on how to perform key workflows with Detection Packs

**Comment by mattthetraveler** [comment]
FYI created this master epic to track overall progress of Detection Packs

**Comment by mattthetraveler** [comment]
Removing this epic and instead tracking progress through the MVP and MMP epics. Sorry for the confusion!
