### ISSUE TITLE
Declaring YAML Schemas [MMP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2633]
> **_Note:_** This is the main Epic. There may be sub-epics to track the phases of feature completion.

## Description

As we simplify the ability for our users to consume managed by publishing schemas to an external repository, we need enhance the Panther UI so users can easily view and manage schemas and automate our schema documentation creation process to Panther can publish schemas more efficiently.

This epic covers MMP features related to declaring YAML schemas in the Panther UI.

## RFC

[RFC](https://github.com/panther-labs/panther-enterprise/blob/e16ecb2ff8d6b099e88f88395a2864f4aaee2106/designs/data_processing/managed_schemas/README.md)

## Design

TBD

## Status and Stakeholders

- [x] Epic created [product] @mattthetraveler 
- [x] RFC written [feature owner] @alxarch 
- [ ] Frontend assigned [frontend] TBD
- [ ] Designs mocked [designer] @dimitriszoitas 
- [ ] Stories planned [fe/be] @alxarch 
- [ ] Stories executed [fe/be] @alxarch 
- [ ] Validation [product/feature owner] @alxarch @mattthetraveler 

#### User Story

As an analyst, 
I want to view Panther-defined schemas and schemas that I've defined in the Panther UI
So I can easily view and manage all custom schemas in one simplified view

#### Acceptance Criteria

- Users should be able to view Panther-defined schemas and user-defined schemas in the "Schemas" sub-tab in the Analysis tab
- Users should be able to filter on "Managed" schemas in the "Schemas" sub-tab as well as
  - Prefix or if possible search on schema id / description
  - Schema Kind (log event, cloud security, scheduled query)
  - Schema Origin (user-defined/panther-managed)
  - Schema Active status (schemas required by active sources, scheduled queries)
  - Schema Enabled status (a user can choose to disable/hide a schema if it is not in use by any active sources)
  - Schema Deleted status (TBD further investigation into what a deleted schema is and how it's handled)
- User should not be able to update/edit any "managed" schemas, they should only be able to view them

#### User Story

As a security engineer
I want to update schemas that Panther has defined in the Panther UI
So I don't have to update the schemas from the external repository

#### Acceptance Criteria

- Create a section in the "Settings" tab where the user can view Panther-defined schema updates and implement them as needed

#### User Story

As a Panther engineer/sales engineer
I want to be able to easily push new managed schemas or schema updates into the public repository
So I don't manually have to test out schemas and create documentation

#### Acceptance Criteria

- Panther employees should be able to easily create managed schemas in the public repository and have documentation and testing done automatically.

#### User Story

As a security engineer
I want to view the latest schemas in Panther's docs per the latest managed schemas updates that Panther pushes
So I can reference the latest supported log schemas

#### Acceptance Criteria

- Users should be able to go to our "supported logs" section in our documentation and see all the latest schemas that Panther supports as we update with new schemas
