### ISSUE TITLE
Usage Metrics in Overview [MVP]

### ISSUE THREAD

**Issue by mattthetraveler** [panther-labs/panther#2652]
## Description

Panther customers have difficulty conceptualizing how much data is processed/stored/retrieved by Panther. Being able to understand these key consumption metrics will help customers understand the value of Panther and what they're paying for.

As a business, can see the cost and usage breakdown as data is processed/stored/retrieved, cloud security accounts are scanned, alerts are generated, and the web-app is used, organized by customer

## RFC

[RFC](https://panther-labs.atlassian.net/wiki/spaces/EN/pages/847806501/RFC+Price+Tracking)

## Design

> **_Note:_** To be updated by the feature owner once completed

## Status and Stakeholders

> **_Note:_** Tag each responsible party below

- [ ] Epic created [product] @mattthetraveler 
- [ ] RFC written [feature owner] @nhakmiller 
- [ ] Frontend assigned [frontend] TBD
- [ ] Designs mocked [designer] @dimitriszoitas 
- [ ] Stories planned [fe/be] @nhakmiller 
- [ ] Stories executed [fe/be] @nhakmiller 
- [ ] Validation [product/feature owner] @nhakmiller @mattthetraveler 

#### User Story

As an engineer
I want to understand how much data is being processed
In an Overview page Data tab
To get a sense of my data ingestion

#### Acceptance Criteria

- A "Data Size Processed by Type" minimal chart displays the database, table name, and table size in either MBs, GBs, or TBs
- A "Total Size" is also displayed at the top, giving an idea of the size of the warehouse
- Allow user to adjust timeframe of the chart in X axis (last month, last week)

#### User Story

As an engineer
I want to understand the size of my stored data
In an Overview page Data tab
To get a sense of Panther's system and log scale

#### Acceptance Criteria

- A "Data Size Stored By Type" minimal chart displays the database, table name, and table size in either MBs, GBs, or TBs
- A "Total Size" is also displayed at the top, giving an idea of the size of the warehouse
- Allow user to adjust timeframe of the chart in X axis (last month, last week)

#### User Story

As a director
I want to understand how many queries i've executed 
In an Overview page Data tab
To get a sense of how much data I've searched through in Panther

#### Acceptance Criteria

- A "Data Queried" that shows how much data has been queried over a specific period of time
  - We need a mechanism that allows us to measure this for Snowflake
- Allow user to adjust timeframe of the chart in X axis (last month, last week)

#### User Story

As a security engineer or analysts
I want to have clear documentation
To use this awesome new functionality

#### Acceptance Criteria

- If a user goes to the docs, they are able to find a page or a section explaining this feature
- If a user finds the docs, they should get a high-level overview followed by a detailed explanation of how this feature works, including arguments, options, caveats, considerations, and tips

**Comment by nhakmiller** [comment]
For the second user story, I think it should be

> I want to understand the size of my stored data

instead of

> I want to understand the size of my incoming data
